---
- name: Configuration du serveur web NovaSphere
  hosts: webservers  # TODO 2 : Groupe défini dans ton inventory/hosts.yml
  become: true      # Exécuter en sudo pour installer des paquets
  
  roles:
    - common
    - webserver
